# The secrets file should not be checked into Git. It's published only for demonstration purpose.
secretGenerator:
  - literals:
      - username=postgres
      - password=postgrespassword
    name: postgres-user-pass
  - literals:
      - password=R00t
    name: mysql-root-pass
  - literals:
      - database=polls
      - url=jdbc:mysql://mysql:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    name: mysql-db-url
resources:
  - backend.yml
  - frontend.yml
  - ingress.yml
  - postgres.yml
images:
  - name: frontend
  - name: backend
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
