apiVersion: v1
kind: PersistentVolumeClaim # Create a PersistentVolumeClaim to request a PersistentVolume storage
metadata: # Claim name and labels
  name: postgres-pv-claim
  labels:
    app: postgres
spec: # Access mode and resource limits
  accessModes:
    - ReadWriteOnce # ReadWriteOnce means the volume can be mounted as read-write by a single Node
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1 # API version
kind: Service # Type of kubernetes resource
metadata:
  name: postgres # Name of the resource
  labels: # Labels that will be applied to the resource
    app: postgres
spec:
  ports:
    - port: 5432
  selector: # Selects any Pod with labels `app=polling-app,tier=mysql`
    app: postgres
---
apiVersion: apps/v1
kind: Deployment # Type of the kubernetes resource
metadata:
  name: postgres # Name of the deployment
  labels: # Labels applied to this deployment
    app: postgres
spec:
  selector:
    matchLabels: # This deployment applies to the Pods matching the specified labels
      app: postgres
  strategy:
    type: Recreate
  template: # Template for the Pods in this deployment
    metadata:
      labels: # Labels to be applied to the Pods in this deployment
        app: postgres
    spec: # The spec for the containers that will be run inside the Pods in this deployment
      containers:
        - image: postgres:13-alpine # The container image
          name: postgres
          env: # Environment variables passed to the container
            # - name: MYSQL_DATABASE
            #   valueFrom:
            #     secretKeyRef:
            #       name: mysql-db-url
            #       key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-user-pass
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-user-pass
                  key: password
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432 # The port that the container exposes
              name: postgres
          volumeMounts:
            - name: postgres-persistent-storage # This name should match the name specified in `volumes.name`
              mountPath: /var/lib/postgresql/data
      volumes: # A PersistentVolume is mounted as a volume to the Pod
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
